static const EMURLProtocol *url_protocols[] = {
    &em_async_protocol,
    &em_cache_protocol,
    &em_data_protocol,
    &em_ffrtmphttp_protocol,
    &em_file_protocol,
    &em_ftp_protocol,
    &em_hls_protocol,
    &em_http_protocol,
    &em_http_proxy_protocol,
    &em_http_s_protocol,
    &em_ijkhttphook_protocol,
    &em_ijklongurl_protocol,
    &em_ijkmediadatasource_protocol,
    &em_ijksegment_protocol,
    &em_ijktcphook_protocol,
    &em_pipe_protocol,
    &em_rtmp_protocol,
    &em_rtmpt_protocol,
    &em_tcp_protocol,
    &em_tls_openssl_protocol,
    &em_udp_protocol,
    &em_udplite_protocol,
    &em_emmul_protocol,
    NULL };
